language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
dist: trusty
script: bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.03 DEPOPTS=xenctrl
  - OCAML_VERSION=4.02
  - OCAML_VERSION=4.01 DEPOPTS=xenctrl
  - OCAML_VERSION=4.00
